### ISSUE TITLE
Freeze copy if value is nil

### ISSUE THREAD

**Issue by shabanovtg** [ghmcadams/redis-utils#4]
![image](https://user-images.githubusercontent.com/6978754/45022524-27154880-b03d-11e8-958f-42127cc246bd.png)
![image](https://user-images.githubusercontent.com/6978754/45022598-5035d900-b03d-11e8-9b0c-3d933a1ef185.png)
![image](https://user-images.githubusercontent.com/6978754/45022668-78253c80-b03d-11e8-8dc0-20cca34b6b0c.png)

**Comment by ghmcadams** [comment]
Closing stale issue.
